spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8
    username: root
    password: 123456
    # 初始化大小,最小，最大
    dbcp2:
      initial-size: 5
      min-idle: 5
      # 配置隔多久才进行一次检测，检测需要关闭的空闲链接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个链接在池中的最小生存时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: select 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上的PSCache的大小
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      # 配置监控统计拦截的filters，去掉监控界面sql将无法统计，‘wall’用于防火墙
      filters: stat,wall,log4j
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      # 合并多个DruidDataSource的监控数据
      # useGlobalDataSourceStat=true
      # 配置获取连接时等待超时的时间
      max-wait-millis: 60000

