server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
  #hibernate ddl auto (validate|create|create-frop|update)
    hibernate:
      ddl-auto: update
  profiles:
    active: dev