server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
  #hibernate ddl auto (validate|create|create-frop|update)
    hibernate:
      ddl-auto: update
  profiles:
    active: dev
minio:
  endpointDownload: http://file.zhiji.gov.cn #对象存储服务的
  endpointUpload:  http://192.168.35.128:9000
  accessKey: telchina #Access key就像用户ID，可以唯一标识你的账户。
  secretKey: telchina@123 #Secret key是你账户的密码。
  expires: 86400 #60 * 60 * 24（一天）  有效时间 单位：秒
  putExpires: 180 #60 * 3（三分钟）
  bucketName:
    imageBucketName: image1
